{
 "title": "Tempo Traces Overview - Tutorial",
 "tags": [
  "tempo",
  "traces",
  "observability",
  "tutorial"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Trazas por segundo por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "{ } | rate() by (resource.service.name)"
    }
   ]
  },
  {
   "title": "Trazas con error por servicio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ status = error } | rate() by (resource.service.name)"
    }
   ]
  },
  {
   "title": "Trazas lentas",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "query": "{ trace:duration > 1s }", "tableType": "traces" }
   ]
  },
  {
   "title": "Trazas con error",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "query": "{ status = error }", "tableType": "traces" }
   ]
  },
  {
   "title": "Servicios con muchos spans muy rapidos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ span:duration < 5ms } | count_over_time() by(resource.service.name) | topk(10)"
    }
   ]
  }
 ]
}