name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install commitlint
        run: npm ci
        working-directory: app

      - name: Lint PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: app/commitlint.config.cjs
